### ISSUE TITLE
MiD-360

### ISSUE THREAD

**Issue by fratopa** [Livox-SDK/livox_ros2_driver#25]
Hello,

I have just ordered a few of the new Mid-360 and I am hoping to use them in ROS. Do you have any idea of when this driver is going to support the new sensors?

**Comment by Nyarn-WTF** [comment]
Hello.

Did you mean: https://github.com/Livox-SDK/livox_ros_driver2

**Comment by fratopa** [comment]
Thank you very much, I guess I posted the issue a few hours before the new drivers!
