### ISSUE TITLE
CustomMsg is invalid.

### ISSUE THREAD

**Issue by Griwa88** [Livox-SDK/livox_ros2_driver#28]
Platform: ROS2 HUMBLE
I have both livox_ros2_driver and livox_ros_driver2 in my ws_livox

Livox Avia puts out PointCloud2 messages and Custom messages without issue.
PointCloud2 is nicely visualized in RviZ
'ros2 topic echo --once /livox/lidar' returns one custom message without issue under 'livox_interfaces/msg/CustomMsg'

Livox HAP puts out a PointCloud2 message without issue, but I cannot read the Custom message.
PointCloud2 is nicely visualized in RviZ
'ros2 topic echo --once /livox/lidar' returns 'The message type "livox_ros_driver2/msg/CustomMsg" is invalid'

Any suggestions?

**Comment by FPSychotic** [comment]
There is a new driver ROS2 for HAP and mid360

**Comment by Griwa88** [comment]
I am running latest livox_ros2_driver for Avia, and latest livox_ros_driver2 for HAP. Issue is more towards livox_ros_driver2, but I am not sure if they are related as I am running both.

**Comment by FPSychotic** [comment]
You should to use driver2 for HAP with ros1 or ros2, and ros2_driver only
with the Avia, so it looks you are doing right. Good luck in that.

**Comment by Griwa88** [comment]
I rebuilt from scratch, seems to have solved the issue.
