### ISSUE TITLE
colcon build

### ISSUE THREAD

**Issue by azeaa** [Livox-SDK/livox_ros2_driver#33]
Starting >>> livox_interfaces
Starting >>> livox_sdk_vendor
--- stderr: livox_sdk_vendor                                         
Traceback (most recent call last):
  File "/opt/ros/dashing/share/ament_cmake_core/cmake/core/package_xml_2_cmake.py", line 21, in <module>
    from catkin_pkg.package import parse_package_string
ModuleNotFoundError: No module named 'catkin_pkg'
CMake Error at /opt/ros/dashing/share/ament_cmake_core/cmake/core/ament_package_xml.cmake:94 (message):
  execute_process(/home/ze/anaconda3/bin/python3
  /opt/ros/dashing/share/ament_cmake_core/cmake/core/package_xml_2_cmake.py
  /home/ze/ws_livox/src/livox_sdk_vendor/package.xml
  /home/ze/ws_livox/build/livox_sdk_vendor/ament_cmake_core/package.cmake)
  returned error code 1
Call Stack (most recent call first):
  /opt/ros/dashing/share/ament_cmake_core/cmake/core/ament_package_xml.cmake:49 (_ament_package_xml)
  /opt/ros/dashing/share/ament_cmake_core/cmake/core/ament_package.cmake:63 (ament_package_xml)
  CMakeLists.txt:49 (ament_package)

---
Failed   <<< livox_sdk_vendor [0.37s, exited with code 1]
Aborted  <<< livox_interfaces [0.49s]                           
                                
Summary: 0 packages finished [0.69s]
  1 package failed: livox_sdk_vendor
  1 package aborted: livox_interfaces
  2 packages had stderr output: livox_interfaces livox_sdk_vendor
  1 package not processed

**Comment by vico1999-ros** [comment]
my system is ubuntu 22.04  ROS2 humble，  use "colcon build" to build the package .find the third file can't finished.  


 [with T = pcl::PointCloud<pcl::PointXYZI>]’
/home/vico/lidar_WS/ws_livox/src/livox_ros2_driver/livox_ros2_driver/lddc.cpp:323:29:   required from here
/usr/include/c++/9/type_traits:2378:11: error: no type named ‘type’ in ‘struct std::enable_if<false, void>’
 2378 |     using enable_if_t = typename enable_if<_Cond, _Tp>::type;
      |           ^~~~~~~~~~~
In file included from /opt/ros/humble/include/rclcpp/rclcpp/topic_statistics/subscription_topic_statistics.hpp:31,
                 from /opt/ros/humble/include/rclcpp/rclcpp/subscription.hpp:50,
                 from /opt/ros/humble/include/rclcpp/rclcpp/any_executable.hpp:25,
                 from /opt/ros/humble/include/rclcpp/rclcpp/memory_strategy.hpp:25,
                 from /opt/ros/humble/include/rclcpp/rclcpp/memory_strategies.hpp:18,
                 from /opt/ros/humble/include/rclcpp/rclcpp/executor_options.hpp:20,
                 from /opt/ros/humble/include/rclcpp/rclcpp/executor.hpp:37,
                 from /opt/ros/humble/include/rclcpp/rclcpp/executors/multi_threaded_executor.hpp:25,
                 from /opt/ros/humble/include/rclcpp/rclcpp/executors.hpp:21,
                 from /opt/ros/humble/include/rclcpp/rclcpp/rclcpp.hpp:155,
                 from /home/vico/lidar_WS/ws_livox/src/livox_ros2_driver/livox_ros2_driver/lddc.h:32,
                 from /home/vico/lidar_WS/ws_livox/src/livox_ros2_driver/livox_ros2_driver/lddc.cpp:25:
/opt/ros/humble/include/rclcpp/rclcpp/publisher.hpp:322:3: note: candidate: ‘template<class
