### ISSUE TITLE
Is it better to unify newline code?

### ISSUE THREAD

**Issue by taichiH** [Livox-SDK/livox_ros2_driver#7]
In this commit, newline code has changed in some file. I guess these files are written by windows system.
https://github.com/Livox-SDK/livox_ros2_driver/commit/213b4ad909b7a3099fb67983b964217ba38d49e4

Currently, codes writtern by unix and windows are mixed in this repository. 
For that differences appear larger than they really are, making it difficult to see important changes.

How about unify newline code?

**Comment by Livox-SDK** [comment]
Hi,taichiH
    The 'CR/LF' and 'LF' mixed bug have been fixed. thanks!
     You can install meld on ubuntu to find out the diffs,thank you for your feedback!
